# Overview

**Learning objectives:**

- Book-club admin
  - Introductions
  - Repository
  - Set-up for contributors

- Explain why JavaScript may be a useful tool for an R developer
- Introduce some
  - JavaScript libraries
  - R packages that use JavaScript
  - JavaScript training material / tutorials

## Rationale

- R & JS have quite different responsibilities

- Why use JavaScript as an R dev
  - JS might have solved your problem
  - JS can do things that R cannot
  - To improve communication of insights

- R packages that use JavaScript
  - [{rmapshaper}](https://github.com/ateucher/rmapshaper) integrates the
  [mapshaper](https://github.com/mbloch/mapshaper/) library
  - [{plotly}](https://github.com/plotly/plotly.R) uses
  [plotly](https://github.com/plotly/plotly.js)
  - [{waiter}](https://github.com/JohnCoene/waiter) based on various JS libraries

## Methods {#integration-methods}

Many ways to integrate JS with R

- Run JS code from R
  - {V8}
  - [V8 on CRAN](https://cran.r-project.org/web/packages/V8/index.html)
  - Used by {rmapshaper}
  - V8 is a JavaScript engine (used in Chrome and Node.js)

- Send data from R to JS, for viewing in the browser
  - {htmlwidgets}
  - [htmlwidgets on CRAN](https://cran.r-project.org/web/packages/htmlwidgets/index.html)
  - Send data from R to JS for viewing in the browser
  - Used to wrap JS visualisation libraries
  - Used by {plotly}, {DT}, {highcharter}

- Pass data back & forth between R and the browser
  - {shiny}
  - e.g., {waiter}

## Methods Amiss

Things that aren't covered by the book

- Send data from R to a specific front-end JS framework
  - React
    - See [{reactR}](https://cran.r-project.org/web/packages/reactR/index.html)
    - ... and its use in[{reactable}](https://cran.r-project.org/web/packages/reactable/index.html)
  - Vue
    - See [{vueR}](https://vue-r.github.io/vueR/)

- Use existing R packages to send data to a JS data visualisation library
  - D3
    - See [{r2d3}](https://rstudio.github.io/r2d3/)

## Some code

Plotly example

- Run the following
- Investigate the plot
- Look at the HTML in DevTools (id="htmlwidget-<randomstring>")
- See where the htmlwidget script is read in

```{r ch1-plotly-example}
suppressPackageStartupMessages({
  library(plotly)
})

plot_ly(
  diamonds,
  x = ~cut,
  color = ~clarity,
  type = "histogram",
  width = "100%"
)
```

## Resources

- Awesome-JavaScript
  - [Data visualisation section](https://github.com/sorrycc/awesome-javascript#data-visualization)

- MDN
  - [JavaScript guides / tutorials](https://developer.mozilla.org/en-US/docs/Web/JavaScript)

- [JavaScript 4 Shiny Field Notes](https://connect.thinkr.fr/js4shinyfieldnotes/)

- [Using htmlwidgets in Rmarkdown](https://bookdown.org/yihui/rmarkdown/html-widgets.html)

## Meeting Videos

### Cohort 1

`r knitr::include_url("https://www.youtube.com/embed/URL")`

<details>
<summary> Meeting chat log </summary>

```
00:18:47	Russ Hyde:	https://r4ds.io/js4r
00:20:46	Arthur Shaw:	https://github.com/r4ds/bookclub-js4r
00:34:26	Ryan Metcalf:	https://mermaid-js.github.io/mermaid/#/
00:34:58	Arthur Shaw:	Looks like DiagrammeR does indeed use mermaid.js. Not sure if for all or only part. https://github.com/rich-iannone/DiagrammeR/tree/main/inst/htmlwidgets/lib/mermaid
00:37:01	Ryan Metcalf:	Excellent comment Arthur. I was going to post a method of code snippet calling on JS. Maybe sometime soon in our bookdown output.
00:53:15	Ryan Metcalf:	My links are scrapped from Twitter….I'm not as familiar with React as with Node.js. https://nextjs.org/
00:53:38	LUCIO ENRIQUE CORNEJO RAMÍREZ:	is the bidirectional communication only available when using Shiny? Or do other methods to integrate JS and R also allow for such communication?
00:53:42	Ryan Metcalf:	https://immerjs.github.io/immer/
00:53:56	Ryan Metcalf:	https://reactjs.org/tutorial/tutorial.html
00:58:20	Ryan Metcalf:	Great question Lucio. My gut instinct answer is no. Any JS engine should be available. However, I may be misinterpreting the "WebServer" that Shiny / RStudio use by default.
00:59:12	Ryan Metcalf:	As a continuation, I would say, any "WebServer" via: React, Python, R, Ruby, Ruby on Rails, NodeJS, etc.... should provide a similar relationship.
01:00:41	LUCIO ENRIQUE CORNEJO RAMÍREZ:	Thanks, Ryan !
01:01:52	Ryan Metcalf:	I'm still forming a method to give better guidance. Stick with me and I'll likely find a more direct answer.
01:08:08	Rhian:	Awesome - thanks Russ 
01:08:57	Arthur Shaw:	https://ambiorix.dev/ ?
01:13:51	Russ Hyde:	Thanks everyone
```
</details>
